# Generated by Django 6.0.6 on 2026-06-21 07:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_competencia_category_equipo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('confirmar', 'Confirmar'), ('corregir', 'Corregir'), ('descalificar', 'Descalificar')], max_length=15, verbose_name='Acción')),
                ('valor_anterior', models.JSONField(verbose_name='Valor anterior')),
                ('valor_nuevo', models.JSONField(verbose_name='Valor nuevo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Auditoría de Registro',
                'verbose_name_plural': 'Auditorías de Registros',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de competencia'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='confianza_ocr',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confianza OCR (%)'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='dorsal_corregido',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dorsal corregido'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='dorsal_detectado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dorsal detectado'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='estado',
            field=models.CharField(choices=[('validado', 'Validado'), ('pendiente', 'Pendiente'), ('corregido', 'Corregido'), ('descalificado', 'Descalificado')], default='validado', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='evidencia_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia (imagen)'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='motivo_descalificacion',
            field=models.TextField(blank=True, verbose_name='Motivo de descalificación'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='origen',
            field=models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='manual', max_length=15, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='validado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación'),
        ),
        migrations.AddField(
            model_name='registrotiempo',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to='app.juez', verbose_name='Validado por'),
        ),
        migrations.AddIndex(
            model_name='registrotiempo',
            index=models.Index(fields=['estado', 'created_at'], name='app_registr_estado_ca67da_idx'),
        ),
        migrations.AddField(
            model_name='auditoriaregistro',
            name='juez',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='app.juez', verbose_name='Juez'),
        ),
        migrations.AddField(
            model_name='auditoriaregistro',
            name='registro_tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='app.registrotiempo', verbose_name='Registro de tiempo'),
        ),
        migrations.AddIndex(
            model_name='auditoriaregistro',
            index=models.Index(fields=['registro_tiempo', 'creado_en'], name='app_auditor_registr_a97d45_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaregistro',
            index=models.Index(fields=['juez', 'creado_en'], name='app_auditor_juez_id_fe13a0_idx'),
        ),
    ]
